### ISSUE TITLE
Simpler default workflow

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/curation_concerns#1031] opened 2016-09-23 15:16 UTC
One step of mediation, with the capability to return it to the initial state.

**Comment by vantuyls** [comment] 2016-10-17 15:23
likely duplicate of #1035 - @jcoyne @mjgiarlo can we close this?

**Comment by mjgiarlo** [comment] 2016-10-17 15:59
@vantuyls As I read it, #1031 was building on #1035, but I ultimately defer to @jcoyne or @jeremyf as to whether or this ticket is functionally identical to #1035.

**Comment by jeremyf** [comment] 2016-10-24 14:29
@mjgiarlo I believe these are different.

**Comment by jcoyne** [comment] 2016-10-24 15:24
Agreed, they were different. However, it's unclear how we deliver both #1031 and #1035. Which workflow should we generate?

**Comment by mjgiarlo** [comment] 2017-01-10 17:32
We have this workflow in Sufia and Hyrax now. Closing.

**Closed by mjgiarlo** 2017-01-10 17:32 UTC
Labels: mediated deposit, ready, workflow
